### ISSUE TITLE
Add license with a widget in Hextra

### ISSUE THREAD

**Issue by MaxwellJay256** [HITSZ-OpenAuto/hoa.moe#20]
I notice that there is a widget that can display a string in Hextra theme.
Like this:

<img width="1130" alt="image" src="https://github.com/HITSZ-OpenAuto/hitsz-openauto.github.io/assets/107470012/52dabba9-aec9-4434-9725-8bb0240f16b8">

This is a site using Hextra I found on https://imfing.github.io/hextra/showcase/.

Can we add the CC-BY-NC-SA 4.0 license with this feature?

**Comment by xiln7** [comment]
Yes you can if you modify the [file](https://github.com/HITSZ-OpenAuto/hitsz-openauto.github.io/blob/main/content/_index.zh-cn.md). Also you might need to refer to the example [here](https://github.com/imfing/hextra/blob/main/exampleSite/content/_index.zh-cn.md).

**Comment by kowyo** [comment]
Licence 应该添加到每个仓库以及每个页面的页脚：https://github.com/santisoler/cc-licenses/blob/main/LICENSE-CC-BY-NC-SA

**Comment by kowyo** [comment]
Here is an update of https://github.com/HITSZ-OpenAuto/hoa.moe/issues/20 and https://github.com/HITSZ-OpenAuto/hoa.moe/pull/91:

I could append the text below to implement this in ‘sponsor.txt’, to have a similar effect with [hugo-theme-stack](https://demo.stack.jimmycai.com/p/hello-world/) and [ruanyifeng's blog](http://www.ruanyifeng.com/blog/2024/05/weekly-issue-301.html), let me know which is better or could we make some enhancement based on this, @longlin10086 and other maintainers.

```
© [署名-非商业性使用-相同方式共享 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

{{< callout type="" >}}
  © 版权声明：[署名-非商业性使用-相同方式共享 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
{{< /callout >}}

{{< callout type="info" >}}
  © 版权声明：[署名-非商业性使用-相同方式共享 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
{{< /callout >}}
```

Effect:

![Screenshot 2024-05-24 at 1 22 03 PM](https://github.com/HITSZ-OpenAuto/hoa.moe/assets/110339237/51694116-e520-42f2-9116-17ceb2757d5b)

**Comment by MaxwellJay256** [comment]
The first and second one looks good.

**Comment by longlin10086** [comment]
would like to choose the 2nd one.

**Comment by kowyo** [comment]
Will close the issue if https://github.com/HITSZ-OpenAuto/hoa.moe/commit/4019e10864cad47b6cae097333c796ca04a38c42 looks good to you. Otherwise we can still have some work on it.
