### ISSUE TITLE
Version control through github release

### ISSUE THREAD

**Issue by longlin10086** [HITSZ-OpenAuto/hoa.moe#22]
We can take version control to this repo by using github release.
Simultaneously announcing the new changes/features to the public.

**Comment by xiln7** [comment]
Great idea! I think most of our users check their email from time to time, let alone their GitHub home while the notification of QQ mail on QQ App does help a lot for our users to get notified for the latest changes. So in my opinion a email notification might be more helpful than the GitHub release.

Plus, I wonder if there is a QQ bot that can notify the updates of OpenAuto in the QQ Group ‘自救群'. I remember there used to be such bot when ChatGPT just released. I will do more investigation on winter holiday.

**Comment by kowyo** [comment]
Here is an update of this issue, maybe https://github.com/marketplace/actions/gh-release could help with this.
