### ISSUE TITLE
前端好像裂开了

### ISSUE THREAD

**Issue by Cherrling** [HITSZ-OpenAuto/hoa.moe#42]
2024年2月6日01点17分
Chrome控制台报错Failed to find a valid digest in the 'integrity' attribute for resource 'https://hoa.moe/css/compiled/main.min.094447ae05896a4615e08d3ae2342011a66e2393febfa3a4befc6e8ff0d38635.css' with computed SHA-256 integrity '3FFRFRbVRGswqccbECegGR8ivNE2g2BTKEn3KdXBfeQ='. The resource has been blocked.

![image](https://github.com/HITSZ-OpenAuto/hoa.moe/assets/37233261/da93e1be-3865-4de0-8947-439c53672b35)

**Comment by longlin10086** [comment]
请问该情况是否能稳定复现？我在本地浏览器中测试均能正常访问

**Comment by Cherrling** [comment]
目前仍确认稳定复现

**Comment by kowyo** [comment]
感谢反馈，当天其实已经修复了。出现这个问题是因为 Cloudflare 的 Rocket Loader 加速服务阻止了一些组件的加载
