### ISSUE TITLE
个人博客文章推荐：《你缺失的那门计算机课》

### ISSUE THREAD

**Issue by IcyDesert** [HITSZ-OpenAuto/hoa.moe#64]
网址 [你缺失的那门计算机课](https://www.criwits.top/missing/)
这是一份写的不错的计算机入门指南，正如开篇而言，它面向「电脑小白」讲解一些比较常用的计算机入门知识，既让读者大致了解计算机的组成与工作原理，又为好奇心很强的读者提供**探索计算机的一些方向**（术语/领域之类），而不至于面对这个精妙的系统迷茫、无从下手。

如题所言，我只是推荐，并不是作者，因此需要询问编委会的意见。这是编委会的电子邮箱：missing@criwits.top 。

By the way，编委会成员 Hans Wan 也有自己的个人博客 https://www.criwits.top/about ，或许也可以询问一下他，是否将其添加至友链？

**Comment by longlin10086** [comment]
可以的，这个我之前也看过，讲得很好
我们会考虑把它作为友链呈现

**Comment by kowyo** [comment]
首先，项目采用  [CC BY-NC-SA]( CC BY-NC-SA) 协议，添加友链甚至不构成内容上的分享，而是基本的引用。

**Comment by kowyo** [comment]
不过还是谢谢你的贡献和建议，如果可以的话你可以参考我们的友链文档提交一个 PR，我们会帮你 merge 的

**Comment by longlin10086** [comment]
友链已添加
