### ISSUE TITLE
Add icon for OpenAuto

### ISSUE THREAD

**Issue by kowyo** [HITSZ-OpenAuto/hoa.moe#69]
The website is still using the icon of Hextra. Hope someone could help design an icon for the website as well as OpenAuto organization.

**Comment by MaxwellJay256** [comment]
I don't have much experience in designing ...
Is starting a solicitation among students a good idea?

**Comment by kowyo** [comment]
I guess this is done in https://github.com/HITSZ-OpenAuto/hoa.moe/commit/b23d7bfb5045ef4adbcccc5b2c7305e606b30f27.
Clear the cache of your browser and see!

**Comment by kowyo** [comment]
I have managed to test the new icon on multiple platforms. I will close it now.

**Comment by kowyo** [comment]
Collecting logo through users in this way can be difficult, as many users of our website don't know how to use GitHub. My initial idea would be creating a poster on our website for collection, while our website still misses something like board. So I may try to ask help from artists in Open-Source community recently, hope that helps.

**Comment by kowyo** [comment]
It is implemented in #78
