### ISSUE TITLE
体育、跨专业选修课学期归属问题

### ISSUE THREAD

**Issue by MaxwellJay256** [HITSZ-OpenAuto/hoa.moe#74]
体育、跨专业选修课，尤其是跨专业选修课，应该不归属于哪个特定的学期，开课时也不针对某个特定年级的学生。
能否将体育和跨专业选修课从各个 semester 文件夹中独立出去？

**Comment by kowyo** [comment]
可以，你可以在新增一个分类之后交一个 PR

**Comment by longlin10086** [comment]
跨专业选修课可以单独拎出去，体育暂时还是维持现状？

**Comment by longlin10086** [comment]
我觉得MOOC也需要单独开设一个界面，同时搜集存放一些答案

**Comment by longlin10086** [comment]
已实现该功能
