### ISSUE TITLE
The download part should be enhanced

### ISSUE THREAD

**Issue by longlin10086** [HITSZ-OpenAuto/hoa.moe#75]
<img width="699" alt="截屏2024-04-24 00 51 28" src="https://github.com/HITSZ-OpenAuto/hoa.moe/assets/110278150/51b1daad-374a-4cd9-aec1-57c1b64eecf0">

When there contains no downloading data, it is ugly to show the empty box to the public.
Need someone to improve it.

**Comment by longlin10086** [comment]
I have created a pr for it, hope it works. https://github.com/HITSZ-OpenAuto/hoa.moe/pull/77

**Comment by kowyo** [comment]
It works. Great!
