### ISSUE TITLE
A noticeboard to publish the news

### ISSUE THREAD

**Issue by longlin10086** [HITSZ-OpenAuto/hoa.moe#76]
Now it is hard for public to find the new changes, therefore we need a noticeboard which contains top 3 or more newest changes with a date and a brief description.

**Comment by longlin10086** [comment]
I have an idea about whether can we add a float block whose 1/4 can be shown on the right website, and when we click it, the all board will move fluently to the public, if click again, the board will be hiden to the original place.

**Comment by OliverWu515** [comment]
> I have an idea about whether can we add a float block whose 1/4 can be shown on the right website, and when we click it, the all board will move fluently to the public, if click again, the board will be hiden to the original place.

你说的有点像教务系统的课表显示的方式，只不过需要一个显眼一点的标识

**Comment by MaxwellJay256** [comment]
![image](https://github.com/HITSZ-OpenAuto/hoa.moe/assets/107470012/74b6d62d-dc0b-428e-955d-02e92dce546e)

嘉立创（难视）

**Comment by kowyo** [comment]
我的想法是把最新文章/文档更新以及日期放到当前的 Feature Card 的位置，做成一个 list

**Comment by longlin10086** [comment]
I think the most diffcult part will be how to adjust the mobile device for the both.
We should discuss it in precise later.

**Comment by longlin10086** [comment]
After a heated discussion, we decided to make this noticeboard into a independent page.

**Comment by kowyo** [comment]
I guess it is done now. Any features to be added?
