### ISSUE TITLE
The action had crashed

### ISSUE THREAD

**Issue by longlin10086** [HITSZ-OpenAuto/hoa.moe#84]
https://github.com/HITSZ-OpenAuto/hoa.moe/actions/runs/9021748054
I guess the reason is that there are no match categories in content directory. Need someone fix it up.

**Comment by longlin10086** [comment]
This had been done in https://github.com/HITSZ-OpenAuto/hoa.moe/pull/85
But a new bug happens.
<img width="771" alt="截屏2024-05-10 09 49 14" src="https://github.com/HITSZ-OpenAuto/hoa.moe/assets/110278150/509bb816-6092-4d41-947f-bda95dbb5eec">

**Comment by kowyo** [comment]
I will fix it later tonight.

**Comment by longlin10086** [comment]
It finally fixed in https://github.com/HITSZ-OpenAuto/hoa.moe/pull/87
